name: Validation when pull request

on:
  push:
    branches: [main, docker-prisma]
  pull_request:
    branches: [main, docker-prisma]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run tests with threshold coverage
        run: npx jest
      - name: Run ESLint
        run: |
          npm run lint -- --max-warnings 20
